export const BG_STYLES = [
  { id:'a',  label:'A',  name:'Grid Glow' },   { id:'b',  label:'B',  name:'Gold Stripe' },
  { id:'c',  label:'C',  name:'Photo Fade' },  { id:'d',  label:'D',  name:'Gold Band' },
  { id:'e',  label:'E',  name:'Conic Burst' }, { id:'f',  label:'F',  name:'Dark Stripe' },
  { id:'g',  label:'G',  name:'Radial Top' },  { id:'h',  label:'H',  name:'3-Slice' },
  { id:'i',  label:'I',  name:'Vertical' },    { id:'j',  label:'J',  name:'Diag Stripe' },
  { id:'k',  label:'K',  name:'Gold Burst' },  { id:'l',  label:'L',  name:'Edge Glow' },
  { id:'m',  label:'M',  name:'3-Band' },      { id:'n',  label:'N',  name:'Conic Twist' },
  { id:'o',  label:'O',  name:'Cream Split' }, { id:'p',  label:'P',  name:'Triple Diag' },
  { id:'q',  label:'Q',  name:'Column' },      { id:'r',  label:'R',  name:'Corner Radial' },
  { id:'s',  label:'S',  name:'Gold Corner' }, { id:'t',  label:'T',  name:'Triple Dark' },
  { id:'u',  label:'U',  name:'Centre Rad' },  { id:'v',  label:'V',  name:'Tri-Band' },
  { id:'w',  label:'W',  name:'Vert Stripe' }, { id:'x',  label:'X',  name:'Dark-Gold' },
  { id:'y',  label:'Y',  name:'Dual Radial' }, { id:'z',  label:'Z',  name:'Quad Diag' },
  { id:'aa', label:'AA', name:'Dark 3-tone' }, { id:'ab', label:'AB', name:'Top Radial' },
  { id:'ac', label:'AC', name:'Ivory Block' }, { id:'ad', label:'AD', name:'Corner Conic' },
  { id:'ae', label:'AE', name:'Diag Stack' },  { id:'af', label:'AF', name:'Dual Radial' },
  { id:'ag', label:'AG', name:'Navy-Gold H' }, { id:'ah', label:'AH', name:'Gold Top' },
  { id:'ai', label:'AI', name:'Ring' },        { id:'aj', label:'AJ', name:'3-Corner' },
  { id:'ak', label:'AK', name:'Fine Lines' },  { id:'al', label:'AL', name:'Smooth 3' },
  { id:'am', label:'AM', name:'Radial 85' },   { id:'an', label:'AN', name:'Tri-Stripe' },
  { id:'ao', label:'AO', name:'Conic' },       { id:'ap', label:'AP', name:'Edge Stripe' },
  { id:'aq', label:'AQ', name:'Dual Side' },   { id:'ar', label:'AR', name:'Diag' },
  { id:'as', label:'AS', name:'Texture' },     { id:'at', label:'AT', name:'Tri-Block' },
  { id:'au', label:'AU', name:'Bot Glow' },    { id:'av', label:'AV', name:'Tri-Gold' },
  { id:'aw', label:'AW', name:'Brick Conic' }, { id:'ax', label:'AX', name:'H-Bands' },
  { id:'ay', label:'AY', name:'Thin Bands' },  { id:'az', label:'AZ', name:'Dual Poles' },
  { id:'ba', label:'BA', name:'Soft Col' },    { id:'bb', label:'BB', name:'Deep Rad' },
  { id:'bc', label:'BC', name:'Angled' },      { id:'bd', label:'BD', name:'Gold Rails' },
  { id:'be', label:'BE', name:'Multi Band' },  { id:'bf', label:'BF', name:'Dual Wide' },
  { id:'bg', label:'BG', name:'Gold Grid' },   { id:'bh', label:'BH', name:'Tri-Block' },
  { id:'bi', label:'BI', name:'Dual Dome' },   { id:'bj', label:'BJ', name:'Burst Side' },
];
