import { AppState } from './types';

export const SECTION_ORDERS: Record<string, string[]> = {
  matchday:  ['header', 'title', 'fixtures', 'footer'],
  results:   ['header', 'title', 'results', 'footer'],
  performer: ['header', 'players', 'footer'],
  signing:   ['header', 'player', 'footer'],
  weekend:   ['header', 'title', 'fixtures', 'footer'],
  squad:     ['header', 'title', 'squad', 'footer'],
  sponsor:   ['header', 'title', 'sponsors', 'footer'],
  notice:    ['header', 'title', 'notice', 'footer'],
  custom:    ['header', 'title', 'content', 'footer'],
  monthly:   ['header', 'title', 'fixtures', 'footer'],
  spotlight: ['header', 'spotlight', 'footer'],
};

export const DEFAULT_STATE: AppState = {
  template: 'matchday',
  style: 'a',
  palette: 'heritage',
  performerLayout: '4-player',
  sectionOrder: SECTION_ORDERS['matchday'],
  clubName: 'RIVERSIDE CC',
  clubTagline: 'Est. 1887 · Premier Division',
  logoDataUrl: '',
  titleTop: 'MATCH',
  titleBottom: 'DAY',
  tournamentText: 'Premier Division',
  matchHome: 'Riverside CC',
  matchAway: 'Valley Hawks',
  matchDate: 'Sat 17 May',
  matchTime: '1:00pm',
  matchVenue: 'Home Ground',
  details: ['Sat 17 May', '1:00pm', 'Home Ground', '', ''],
  results: [
    { outcome: 'W', innings1: 'Riverside 187/4 (35)', innings2: 'Valley 143 ao (32)', resultLine: 'Won by 44 runs' },
    { outcome: 'W', innings1: 'Thornton 156/6 (40)', innings2: 'Riverside 158/3 (36)', resultLine: 'Won by 7 wickets' },
    { outcome: 'L', innings1: 'City 210/5 (40)', innings2: 'Riverside 188 ao (38)', resultLine: 'Lost by 22 runs' },
  ],
  resultCount: 3,
  players: [
    { name: 'J. Smith',   role: 'Batsman',      stat: '87* (62)',      photoDataUrl: '' },
    { name: 'A. Hassan',  role: 'Bowler',        stat: '4/28',          photoDataUrl: '' },
    { name: 'T. Clarke',  role: 'All-Rounder',   stat: '45 & 2/30',    photoDataUrl: '' },
    { name: 'S. Wells',   role: 'Wicket-keeper', stat: '34* & 2 ct',   photoDataUrl: '' },
  ],
  playerCount: 4,
  signingName: 'J. Hartley',
  signingRole: 'All-Rounder',
  signingNote: 'Joining from Thornton CC. Welcome to the club!',
  signingPhotoDataUrl: '',
  fixtures: [
    { badge: '1st XI', homeTeam: 'Riverside CC', awayTeam: 'Valley Hawks', time: '1:00pm', date: 'Sat 17 May', venue: 'Home' },
    { badge: '2nd XI', homeTeam: 'Thornton CC', awayTeam: 'Riverside CC', time: '11:00am', date: 'Sun 18 May', venue: 'Away' },
    { badge: '1st XI', homeTeam: 'Riverside CC', awayTeam: 'City CC', time: '2:00pm', date: 'Sat 24 May', venue: 'Home' },
    { badge: '2nd XI', homeTeam: 'Valley Hawks', awayTeam: 'Riverside CC', time: '1:00pm', date: 'Sun 25 May', venue: 'Away' },
    { badge: '1st XI', homeTeam: 'Riverside CC', awayTeam: 'North CC', time: '11:00am', date: 'Sat 31 May', venue: 'Home' },
  ],
  squadPlayers: [
    { name: 'J. Hartley (c)', photoDataUrl: '' },
    { name: 'T. Clarke',      photoDataUrl: '' },
    { name: 'A. Hassan',      photoDataUrl: '' },
    { name: 'S. Wells (wk)',  photoDataUrl: '' },
    { name: 'M. Patel',       photoDataUrl: '' },
    { name: 'D. Johnson',     photoDataUrl: '' },
    { name: 'R. Ahmed',       photoDataUrl: '' },
    { name: 'B. Thompson',    photoDataUrl: '' },
    { name: 'C. Williams',    photoDataUrl: '' },
    { name: 'F. Davies',      photoDataUrl: '' },
    { name: 'G. Roberts',     photoDataUrl: '' },
    { name: 'H. Taylor',      photoDataUrl: '' },
  ],
  noticeText: 'Training cancelled this Thursday due to weather. Next session: Tuesday 6:30pm at the ground.',
  sponsors: [],
  sponsorLayout: 'featured',
  sponsorCount: 'all',
  titleScale: 100,
  titleTopScale: 100,
  titleBotScale: 100,
  headlineX: 0,
  headlineY: 0,
  headlineSpacing: 100,
  detailScale: 100,
  fixtureScale: 100,
  metaScale: 100,
  badgeScale: 100,
  sponsorScale: 100,
  sponsorHeight: 0,
  logoScale: 100,
  logoX: 0,
  logoY: 0,
  topSpacing: 0,
  bgOpacity: 18,
  bgSize: 100,
  bgPosX: 50,
  bgPosY: 50,
  mediaBrightness: 100,
  mediaContrast: 100,
  mediaSaturate: 100,
  bgImageDataUrl: '',
  customNavy: '',
  customBlue: '',
  customGold: '',
  textColor: '#ffffff',
  accentColor: '#d8aa2d',
  onboardingDone: false,
  logoNoBg: false,
  sponsorNoBg: false,
  showHeader: false,
  contentY: 0,
  contentX: 0,
  contentScale: 100,
  imageLayers: [],
  padTop: 0,
  padBottom: 0,
  padLeft: 0,
  padRight: 0,
  ratio: 'story',
};
